#!/usr/bin/env bash

sudo postgresql-setup --initdb
sudo -u postgres -i createuser -d $USER
createdb makerspace

psql makerspace <<EOF

CREATE SCHEMA makerspace;
ALTER DATABASE makerspace SET search_path TO makerspace, pg_catalog;

EOF
