#!/usr/bin/env bash

psql makerspace <<EOF

DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS session_http CASCADE;
DROP TABLE IF EXISTS administrator CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS storage CASCADE;

CREATE TABLE member (
    username text PRIMARY KEY,
    name text NOT NULL,
    password_key character(64) NOT NULL,
    password_salt character(64) NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    email_validated boolean NOT NULL DEFAULT false,
    registered timestamp DEFAULT now()
);
CREATE TABLE session_http (
    token character(64) PRIMARY KEY,
    username text NOT NULL REFERENCES member,
    sign_in_time timestamp NOT NULL DEFAULT now(),
    last_seen timestamp NOT NULL DEFAULT now(),
    expired boolean NOT NULL DEFAULT false
);
CREATE TABLE administrator (
    username text PRIMARY KEY REFERENCES member
);
CREATE TABLE student (
    username text PRIMARY KEY REFERENCES member,
    institution text,
    graduation_date date
);
CREATE TABLE storage (
    location text NOT NULL,
    number integer NOT NULL,
    member text REFERENCES member,
    description text,
    PRIMARY KEY (location, number)
);

EOF
